name: first workflow

on: 
  push: 
    branches:
      -main
  pull_request:
    branches:
      -main
      
  workflow_dispatch:
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print greeting
        run: echo "Hello World!"
        shell: bash
        
      - name: Print goodbye
        run: echo "Done -Bye!"
        shell: bash
      
